name: Build and Test Go Application

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do Go (instalação da versão correta)
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20  # Alterar para a versão do Go que sua aplicação exige

      # Verificar versão do Go (para garantir que está instalado corretamente)
      - name: Verify Go installation
        run: go version

      # Instalação das dependências
      - name: Install dependencies
        run: go mod tidy

      # Build da aplicação
      - name: Build application
        run: go build -v ./...

      # Rodar os testes unitários
      - name: Run tests
        run: go test -v ./...

      # Exibir cobertura de testes (opcional)
      - name: Test coverage
        run: go test -cover ./...
